language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - npm install
script:
    - npm run build
    - pytest tests/

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/bower
        - $HOME/.npm
        - "node_modules"
