language: python
python:
    - "3.6"
    - "3.5"
services:
    - mongodb
before_install:
    - export GECKODRIVER_DOWNLOAD='https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz'
    - curl -L -o /tmp/geckodriver.tar.gz $GECKODRIVER_DOWNLOAD
    - mkdir $HOME/geckodriver && tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
    - export PATH=$HOME/geckodriver:$PATH
    - geckodriver --version
install:
    - . tests/libsodium-install-travis.sh
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - npm install
script:
    - npm run build
    - pytest tests/ --driver Firefox

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/bower
        - $HOME/.npm
        - "node_modules"
